apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-backend-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        image: mikeyhu/k8s-backend:0.1.0
        ports:
        - containerPort: 9090