apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-backend-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        image: mikeyhu/k8s-backend:0.2.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9090

  strategy:
    type: RollingUpdate
  minReadySeconds: 20